# Mapeog del modelo de datos

Correspondencia campos

| Camp API     | Camp intern| Tipus    |
|--------------|------------|----------|
| id           | id         | string   |
| nom          | titol      | string   |
| descripcio   | descripcio | string   |
| categoria    | categoria  | string   |
| preu         | preu       | number   |
| imatge       | imatgeUrl  | string   |
| popular      | esPopular  | boolean  |
| stock        | unitats    | number   |