
# Mapeo del modelo de datos

Correspondencia campos

| Campo API    | Campo interno |   Tipo    |
|--------------|---------------|-----------|
| `id`         | `id`          | String    |
| `nom`        | `titol`       | String    |
| `descripcio` | `descripcio`  | String    |
| `categoria`  | `categoria`   | String    |
| `preu`       | `preu`        | number    |
| `imatge`     | `imatgUrl`    | String    |
| `popular`    | `esPopular`   | Booleano  |
| `stock`      | `unitats`     | number    |
|--------------|---------------|-----------|